name: Gideon1
options:
  bundleIdPrefix: com.taylorolsenvogt
settings:
  base:
    DEVELOPMENT_TEAM: "84U223KLAD"
    SWIFT_VERSION: 6.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
targets:
  Gideon1:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Gideon1
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taylorolsenvogt.Gideon1
        INFOPLIST_FILE: Gideon1/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
  Gideon1Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Gideon1Tests
    dependencies:
      - target: Gideon1
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
schemes:
  Gideon1:
    build:
      targets:
        Gideon1: all
        Gideon1Tests: [test]
    test:
      config: Debug
      commandLineArguments:
        "--isolation-tests": true
      targets:
        - name: Gideon1Tests
          parallelizable: false
